# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HeWeather_WidgetDemo' do
 pod 'SDWebImage'
 pod 'Masonry'

  target 'HeWeather_WidgetDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HeWeather_WidgetDemoUITests' do
    # Pods for testing
  end

end
